### ISSUE TITLE
Multiple sensors using the same pump and db

### ISSUE THREAD

**Issue by chrowe** [open-eio/Open-Pipe-Kit-Project#17]
Use case is that you want multiple data points about a single system or related systems.
It seems like the easiest solution would be to collect a single reading from each related sensor and then send it all together as one record to the db.

**Comment by rjcorwin** [comment]
Here are some notes from discussion with @dwblair and @treehouse-su. We've thought about using a middleman program, thought about chaining with `|`, and thought about how trying to fit multiple sensors into a single data record with one timestamp is a problem that makes fuzzy assumptions. 

Chain:

```
watch -n3 "./driver1/pull --id driver1 | ./driver2/pull --id driver2 | ./driver3/pull --id driver3 | ./driver4/push"
```

Middleman:

```
watch -n3 "./driver1/pull | middleman driver1"
watch -n3 "./driver2/pull | middleman driver2"
watch -n3 "./driver3/pull | middleman driver3"
middleman --config "driver1,driver2,driver3" --csv | ./driver4/push
```

The way it works now where you send 3 separate packets...

```
watch -n3 "./driver1/pull | ./driver4/push --id driver1"
watch -n3 "./driver2/pull |  ./driver4/push --id driver2"
watch -n3 "./driver3/pull | ./driver4/push --id driver3"
```

The idea we're after here, is pushing data in bundled records like...

```
{
  "driver1": 32,
  "driver2": 34,
  "driver3": 33
}
```

Some advantages of pushing 1 packet instead of 3...
1. Minimizing power consumption by sending 1 packet as opposed to 3. 
2. Minimizing bandwidth by sending 1 packet as opposed 3.
3. Storing data in a way that looks better

**Comment by dwblair** [comment]
Great!

Here's an implementation of a 'middleman' approach:

https://github.com/open-eio/sprint-005

The idea is to create a special type of file -- a 'named pipe' or 'FIFO' file -- that allows for interprocess communication.

In the following example, this file is named 'pipefile' , and the CLI that creates and manages it is called 'pipe'.

First, we pull data from a sensor using a 'pull' command, and stores it in the pipefile:

> ./opk-pull-temper -s SENSOR1 | ./pipe -w pipefile

This creates the named pipe 'pipefile', and writes a packet of data from SENSOR1 to it.  Note that for named pipes, no actual writing to disk occurs other than the initial metadata associated with creating the named pipe.  This is an advantage when  using an SD card with a fairly limited lifetime of reads/writes. 

Then, we pull a data packet from a different sensor, and add it to the pipefile:

> ./opk-pull-conduct -s SENSOR2 | ./pipe -w pipefile

Finally, we invoke the pipe CLI command for consolidating the data in 'pipefile' and pushing that data out to a database (in this case, to a 'phant' database, using public + private keys stored in keys.json):

> ./pipe - r pipefile | opk-push-phant -k keys.json

**Comment by dwblair** [comment]
Factored out the code for the 'pipe' CLI above, renamed it 'funnel':

https://github.com/open-eio/opk-funnel

Now it autodetects whether you're trying to funnel data into it (by seeing whether there's anything in sys.stdin) or whether you're trying to funnel data out of it.

Accordingly, to pull in data from sensor1 and sensor2:

> ./pull-sensor1 | ./funnel &

(the '&' is needed in order to avoid the process halting, due to the 'blocking' associated with opening a named pipe)

> /.pull-sensor2 | ./funnel &

then, to get the  combined packet:

> ./funnel --syntax JSON | ./push-database1

The options thus far for --syntax are:  JSON and CSV (with CSV the default).
